########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog
url: https://example.com

owner:
  name: Jane Doe
  bio:
    This is my blog. There are many like it but this
    one is mine.

# A default header image
header:
  image: main.jpg

services:
  google_analytics: UA-XXXXX-Y
  disqus_shortname: EXAMPLE

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README"]

plugins:
  - bootstrap
  - jekyll-assets

sass:
  sass_dir: _sass

collections:
  - resume-cards
  - resume-jobs

# Include comments by default in posts but not pages
defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
  - scope:
      type: "pages"
    values:
      comments: false
