########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog
description:
  This is the personal site of Jane Doe. There are many like it but this one
  is hers.
url: https://example.com
logo: logo.png
logoalt: Every image should have an alt tag, and this one is for the site logo.

owner:
  name: Jane Doe
  bio:
    This is my blog. There are many like it but this
    one is mine.
  twitter: jane_doe  # twitter handle (without the @)
  github: jane_doe  # github handle
  linkedin: jane_doe # linkedin easy name (the part after the /in/ in your URL)
  facebook: jane_doe # facebook easy name

# A default header image
header:
  image: main.jpg
  imagealt: Describe the site header image for screen reader users.

services:
  google_analytics: UA-XXXXX-Y
  disqus_shortname: EXAMPLE

# Category pages
category_dir: /
categories_meta:
  default:
    header:
      image: main.jpg
      imagealt: Describe the default category index header image for screen reader users.
  code:
    long_title: Software Development # Long Title: Optional. Defaults: short title
    description: Thoughts on Software Development # Description: Optional. Default: "Posts in the _ section"
    long_description: These are some of my thoughts on software development. # Long Description: Optional. Default: Description
    header: # Header section. Optional. Defaults to the common default.
      image: main.jpg
      imagealt: Describe the category index header image for screen reader users.
    weight: -1 # Optional, defaults to 0. Negative comes later in navbar list.
      # Weight. Optinal. Default: 0. Positive numbers come earlier in the navbar
      # menu, negative numbers come later.
  life:
    long_title: Life, The Universe, and Everything
    description: So long, and thanks for all the fish

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README", "bin"]

plugins:
  - bootstrap

sass:
  sass_dir: _sass

collections:
  - resume-cards
  - resume-jobs

# Include comments by default in posts but not pages
defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
  - scope:
      type: "pages"
    values:
      comments: false
