########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog
description:
  This is the personal site of Jane Doe. There are many like it but this one
  is hers.
url: https://example.com
logo: logo.png
logoalt: Every image should have an alt tag, and this one is for the site logo.

permalink: "/:categories/:year/:month/:title/"
timezone: UTC

owner:
  name: Jane Doe
  email: jane_doe@example.com
  bio:
    This is my blog. There are many like it but this
    one is mine.
  image: photo.png
  imagealt: A description of your photo for screen reader users.
  imagecolor: ffffff
  twitter: jane_doe  # twitter handle (without the @)
  github: jane_doe  # github handle
  linkedin: jane_doe # linkedin easy name (the part after the /in/ in your URL)
  facebook: jane_doe # facebook easy name

# A default header image
header:
  image: main.jpg
  imagealt: The facade of a modern glass building.
  title: Architecture Modern Building Facade
  title-link: "https://pixabay.com/en/architecture-modern-building-facade-3136963/"
  credit: Michael Gaida
  credit-link: "https://pixabay.com/en/users/MichaelGaida-652234/"
  license: cc0

services:
  google_analytics: UA-XXXXX-Y
  disqus_shortname: EXAMPLE

# Category pages
category_dir: /
categories_meta:
  code:
    long_title: Software Development # Long Title: Optional. Defaults: short title
    description: Thoughts on Software Development # Description: Optional. Default: "Posts in the _ section"
    long_description: These are some of my thoughts on software development. # Long Description: Optional. Default: Description
    weight: -1 # Optinal. Default: 0. Positive numbers come earlier in the navbar
               # menu, negative numbers come later.
    header:
      image: code.jpg
      imagealt: An stylized photo of minified JavaScript source code.
      title: Minified JavaScript Source Code
      title-link: "https://altphotos.com/photo/minified-javascript-source-code-908/"
      credit: Markus Spiske
      credit-link: "https://altphotos.com/authors/markusspiske/"
      license: cc0 # one of cc0, cc-by-2, cc-by-4, cc-ba-sa-4, reserved
  life:
    long_title: Life, The Universe, and Everything
    description: So long, and thanks for all the fish

# Source for render_code
code_dir: code-examples

# How many posts per index page
paginate: 5
paginate_path: "/:num/"

# How many related posts to show. If => total number of posts, the carousel
# behavior will be undefined.
related_count: 2
# Should the related posts section be full_width?
related_wide: true

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README", "CODE_OF_CONDUCT", "bin", "Rakefile", "s3_website.yml"]

plugins:
  - bootstrap

sass:
  sass_dir: _sass

collections:
  - resume-cards
  - resume-jobs

# Include comments by default in posts but not pages
defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
  - scope:
      type: "pages"
    values:
      comments: false
