########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog
url: https://example.com

owner:
  name: Jane Doe
  bio:
    This is my blog. There are many like it but this
    one is mine.

# A default header image
header:
  image: main.jpg

services:
  google_analytics: UA-XXXXX-Y
  disqus_shortname: EXAMPLE

# Category pages
category_dir: /
categories_meta:
  default:
    header:
      image: main.jpg
  code:
    long_title: Software Development
    description: Thoughts on Software Development
    long_description: These are some of my thoughts on software development.
    header:
      image: main.jpg
  life:
    long_title: Life, The Universe, and Everything
    description: So long, and thanks for all the fish
    # long descriptions are optional, and default the the normal one
    # be sure to define colors in _sass/variables.scss to get the corresponding
    # css classes

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README"]

plugins:
  - bootstrap
  - jekyll-assets

sass:
  sass_dir: _sass

collections:
  - resume-cards
  - resume-jobs

# Include comments by default in posts but not pages
defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
  - scope:
      type: "pages"
    values:
      comments: false
