########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog

owner:
  name: Edward Hyde
  bio:
    This is my blog. There are many like it but this
    one is mine.

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README"]
