########## Site Options ##########
title: Euler Pi
title-brand: EulerPi
subtitle: A Blog of Tech, Math, and Geek Stuff

owner:
  name: Charles Beynon
  bio:
    Full Stack Developer mostly working in Rails. Recovering sysadmin. I
    like to dabble and tend to ramble. Don't say I didn't warn you ;D

# A default header image
header:
  image: main.jpg

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README"]

gems:
  - bootstrap
  - jekyll-assets

sass:
  sass_dir: _sass
