########## Site Options ##########
title: My Jekyll Blog
title-brand: MyJekyll
subtitle: Just a blog
url: https://example.com

owner:
  name: Jane Doe
  bio:
    This is my blog. There are many like it but this
    one is mine.

# A default header image
header:
  image: main.jpg

services:
  google_analytics: UA-XXXXX-Y
  disqus_shortname: EXAMPLE

# Category pages
category_dir: /
categories_meta:
  default:
    header:
      image: main.jpg
  code:
    long_title: Software Development
      # Long Title: Optional. Defaults: short title
    description: Thoughts on Software Development
      # Description: Optional. Default: "Posts in the _ section"
    long_description: These are some of my thoughts on software development.
      # Long Description: Optional. Default: Description
    header:
      image: main.jpg
      # Header section. Optional. Defaults to the common default.
    weight: -1 # Optional, defaults to 0. Negative comes later in navbar list.
      # Weight. Optinal. Default: 0. Positive numbers come earlier in the navbar
      # menu, negative numbers come later.
  life:
    long_title: Life, The Universe, and Everything
    description: So long, and thanks for all the fish

# Default extension of new posts and pages
post_ext: md
page_ext: html

# Default layouts for posts and pages
# Found in _layouts/
post_layout: post
page_layout: page

# Default templates on `octopress new`
# Found in _templates/
post_template: post
page_template: page
draft_template: draft

# Don't generate project files in the output site
exclude: ["Gemfile", "LICENSE", "README"]

plugins:
  - bootstrap
  - jekyll-assets

sass:
  sass_dir: _sass

collections:
  - resume-cards
  - resume-jobs

# Include comments by default in posts but not pages
defaults:
  -
    scope:
      type: "posts"
    values:
      comments: true
  - scope:
      type: "pages"
    values:
      comments: false
